### ISSUE TITLE
BE: Mongo for project

### ISSUE THREAD

**Issue by rajivtitus** [hatchways/team-runtime-terror#2]
\- Set up the MongoDB for the project. The goal for this ticket is that the authentication features included in the starting code will be functional by storing user information in the database.

Here are some resources on the technologies:
\- \*\*MongoDB\*\* - use Mongoose for Node.js

**Comment by ibsa-ejeta** [comment]
Hi Team, created a database on mongoDB Atlas please create .env file under the server folder and add the following  and save
MONGO_URI=mongodb+srv://ibsa:teamRuntimeTerror@cluster0.a1seq.mongodb.net/RuntimeTerror?retryWrites=true&w=majority

**Comment by rajivtitus** [comment]
Hi @ibsa-ejeta, this LGTM!

Maybe also create a small PR and add the MONGO_URI (field only) to the sample.env? :)
